### ISSUE TITLE
Optifabric incompatibility

### ISSUE THREAD

**Issue by WilliamSivlar** [enjarai/do-a-barrel-roll#108]
Launching the game on 1.20 gives me an incompatibility error screen saying no version of optifabric is compatible with this mod. Error message displayed below.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.3.2+1.20 with any version that is compatible with:
		 - optifabric 1.13.25
Unmet dependency listing:
	 - Mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.3.2+1.20 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by enjarai** [comment]
This is correct. Optifine breaks this mod in many ways that I haven't been able to diagnose due to its invasive and closed source nature.

Luckily, there's no reason to use Optifine in 2023, as there are [many alternatives](https://lambdaurora.dev/optifine_alternatives/) available to cover features it provides. These alternatives are almost always more compatible with other mods, *and* open source, making it easy for mod authors to work together to maintain a working game.
