### ISSUE TITLE
Iris 1.20.6 incompatibility

### ISSUE THREAD

**Issue by facufachin** [enjarai/do-a-barrel-roll#143]
**Describe the issue**
Crash on startup

**Crash report/logs (if applicable)**
https://mclo.gs/xX1ke6z

**Additional information**
None

**Comment by enjarai** [comment]
Do a Barrel Roll is currently not compatible with Iris on 1.20.6. I'm not sure why this is the case. See https://github.com/IrisShaders/Iris/issues/2319 where I'm trying to get into contact with Iris devs.

**Comment by enjarai** [comment]
We've tracked this issue down to a conflicting mixin caused by internal changes to game code. The way the code changed is actually extremely inconvenient, and means mods that modify camera rotation (which Iris does apparently) will almost inherently conflict now.

We are actively looking into this issue, and a bandaid fix was published with 3.5.8, which does work, but has some issues. Since Iris is leaving this completely up to our side to solve, it might take a while to find a proper workaround.

**Comment by enjarai** [comment]
This issue should be fully resolved as of 3.5.9.
