### ISSUE TITLE
Incompatiblity with WorldEdit

### ISSUE THREAD

**Issue by TanCY1** [enjarai/do-a-barrel-roll#177]
**Describe the issue**
When loading a world with both mods, the game crashes
**Crash report/logs (if applicable)**
[link](https://github.com/EngineHub/WorldEdit/issues/2649)

**Additional information**
Seems to be related to the fabric permissions api bundled with the mod

**Comment by enjarai** [comment]
This is actually not caused by Do a Barrel Roll. Fabric Permissions API has an outdated function that doesn't work on 1.21.3. DABR explicitly *does not* call this function for this exact reason. It seems that worldedit decides to call the function when Fabric Permissions API is available. And since DABR includes the current most up to date version that I'm aware of, this is the result.
