### ISSUE TITLE
Config option to turn off cinematic camera

### ISSUE THREAD

**Issue by Firestrike1** [enjarai/do-a-barrel-roll#19]
Really, why would you think locking people into cinematic camera mode while precise inputs are required from them is a good idea? It can look good, but i'd rather have actual control over my movement.

**Comment by enjarai** [comment]
If you want to try out how it feels without smoothing, you can download the mod this one is inspired by, called Cool Elytra, and enable realistic mode. The main reason I made this mod is because I like that flight system, but it feels really bad without some kind of smoothing.

Because of that, I currently have no plans of implementing a toggle for it.

If you have other arguments aside from indignant superiority, feel free to comment them, but I'm closing this issue for now as not planned.

**Comment by kesakat** [comment]
Since this mod has server side features and a forge port (unlike the Cool Elytra mod) id like to ask that this issue were to be reopened/reconsidered as something to do
 
(unlike OP i ask specifically for this as an accessibility feature, as the smoothing causes headaches after prolonged use of elytra flight for a few people in a server i am a part of. id rather not make anyone switch mods to something with a smoothing option, as the server-sided features would be null, and troubleshooting issues the users may have would be more difficult as they will be using a mod no one else has)

**Comment by enjarai** [comment]
I've actually gotten similar arguments in the past, which is why I did eventually implement a toggle for the smoothing. It's actually been available in the config menu for quite a while now! Unless you're using an ancient version of the mod, you *should* be able to find it there. Let me know if you have any issues!
