### ISSUE TITLE
Bug or Feature? Holding S with thrusting.

### ISSUE THREAD

**Issue by moltenwolfcub** [enjarai/do-a-barrel-roll#41]
The title is pretty self-explanatory but I've found that with the new version you can get near-creative-flight by using thrusting(even at a low value) and holding the walk backwards key.

I was messing around on a survival server(elytraFlyCheck is disabled) and I can't tell if this is intended or a bug. A suggestion for a fix is that the backwards thrust speed could be set to a percentage of the forwards thrust speed(maybe even configurable) or you could just accept this as intended behaviour and leave it as is.

https://user-images.githubusercontent.com/90516933/209095200-acff577b-9843-4f92-9b53-1bc864c74baf.mp4 (excuse my flying skills I'm not the best)

**Comment by enjarai** [comment]
This is intentional. As thrusting is a supplementary feature mostly there for people who just want to use the flight mechanics in a singleplayer world, I figured I'd give as much freedom of movement with it as possible.

The only potential issue I see here is that reversing is a bit too strong compared to going forward, so I might look into that.
