### ISSUE TITLE
server bukkit pulgin pls

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [enjarai/do-a-barrel-roll#90]
Why?
Because some pure servers don't have a way to install this mod, making the server functions of the mod unavailable.

**Comment by enjarai** [comment]
The server-side of this mod is very mixin-heavy, which is something plugins do not support. Due to this, a plugin version would be quite difficult to pull off without deep knowledge of the Spigot API, which I do not have, and am not interested in learning. As such, a first-party plugin version is not planned.
